### ISSUE TITLE
Missing the contribution manual

### ISSUE THREAD

**Issue by Cy6er7um** [Xie-Jason/GloomScript#1]
Will there be a contribution manual?
Im interested in this language and would like to contribute a bit to it, like the Jit support?

**Comment by Xie-Jason** [comment]
Thanks for your star and issue. Contributions are always welcome in this project. I will prepare the development and contribution manual, and I try to finish a simple version of them in recent several days.

**Comment by Cy6er7um** [comment]
> Thanks for your star and issue. Contributions are always welcome in this project. I will prepare the development and contribution manual, and I try to finish a simple version of them in recent several days.

刚刚看了下 发现是国人欸!!! 可以给个联系方式吗?

**Comment by Xie-Jason** [comment]
QQ 1105856628 , Email : xjc223@foxmail.com
