### ISSUE TITLE
New

### ISSUE THREAD

**Issue by czw0818** [Xie-Jason/GloomScript#6]
我对你的项目跟感兴趣.我观看了你上传至b站的视频并简单阅读了项目代码。我有以下建议:
1.类型系统的表示可以改进，我们可以学习rust,python,在变量名后加个冒号再加类型名.当函数作为返回值时可以学习Go语言的标注方法
2.我们可以借用FFI起码能用Rust为它写拓展。
3.闭包函数最好也能在执行时访问全局变量

**Comment by Xie-Jason** [comment]
感谢你对本项目的关注。第一点 我想很多人可能不适应let时变量名和类型名中没有冒号，我稍后会同时支持有无冒号两种语法。第二点 作为一个用Rust写的解释器，支持用Rust写类库是理所应当的，稍后这部分稳定了，我会写一下这部分的文档。第三点 闭包可以访问全局变量，关于全局以及静态变量这部分还没有开发完毕，所以暂时没有展示。所有开发完的功能我都会写入文档。

**Comment by czw0818** [comment]
when the FFI is stable,i am glad to write extern for this project no matter use Rust or the language.还有函数签名返回值语法建议兼容一下Rust,我将持续关注你的项目
